### ISSUE TITLE
Error in my build system

### ISSUE THREAD

**Issue by codev0** [ghosh/Micromodal#95]
Hey, I've caught error, when tried to use this plugin.
Error trace
```
[00:54:01] 'javascript' errored after 1.85 s
[00:54:01] Error in plugin 'webpack-stream'
Message:
    ./~/micromodal/dist/micromodal.es.js
Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "/project/node_modules/micromodal/.babelrc" at 0, attempted to resolve relative to "/project/node_modules/micromodal"
    at /project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/project/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/project/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/project/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/project/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/assets/js/app.js 3:18-39
 @ multi ./src/assets/js/app.js
Details:
    domain: [object Object]
    domainThrown: true
[00:54:01] 'build' errored after 1.87 s
[00:54:01] 'default' errored after 1.87 s
[00:54:01] The following tasks did not complete: sass
[00:54:01] Did you forget to signal async completion?
[1]    57443 segmentation fault  npm run start
```
Gulp config https://gist.github.com/codev0/15dd75634e81a1ae0c59a2a5974c3c0b

devDependencies related to es6
```
"babel-core": "^6.24.1",
"babel-loader": "^6.4.1",
"babel-preset-env": "^1.6.1",
"babel-preset-es2015": "^6.3.13",
"babel-register": "^6.7.2",
"webpack": "^2.6.1",
"webpack-stream": "^3.2.0",
```

**Comment by kelenakamura** [comment]
did you ever fix this? we're seeing same issue on a windows machine. seems fine on all the macs we've run this on.

**Comment by ghosh** [comment]
@kakadiadarpan @kalpeshsingh Any thoughts on this?

**Comment by kakadiadarpan** [comment]
@ghosh I can look into this

@codev0 It would really help a lot if you can provide a simple reproduction of the issue

**Comment by geosigno** [comment]
you can fix this issue by adding: 

`exclude: /node_modules/,`

in your webpack.config.js

**Comment by ghosh** [comment]
Closing this issue now. Feel free to open if your still having issues.
